version: '3.1'
services:
  backend:
    image: my-backend
    networks:
      - beautyservices-network
    ports:
      - "8081:8081"
  db:
    image: postgres:10-alpine
    networks:
      - beautyservices-network
    ports:
    - "5433:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: beauty_services
  admin:
    image: adminer
    networks:
      - beautyservices-network
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
networks:
  beautyservices-network:
    name: beautyservices-network
